services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build: .
    container_name: rag_app
    depends_on:
      - elasticsearch
    ports:
      - 8501:8501   # Streamlit UI
    volumes:
      - .:/app
  
  jupyter:
    image: jupyter/base-notebook:latest
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"

volumes:
  esdata:
    driver: local
